### PR TITLE
Added menu

### LINKED ISSUE #504: integrate menu plugin
Find/add/document menu plugin for reveal.js to aid navigation.

### PR DESCRIPTION
**Pull request by sonukapoor**
Based off https://denehyg.github.io/reveal.js-menu/#/home

Closes #504

### CODE REVIEW

**Comment by gvwilson** [comment]
Can you please include a screenshot?

**Comment by sonukapoor** [comment]
**Screenshot 1:**

image

**Screenshot 2:**

image

**Comment by sonukapoor** [comment]
@gvwilson can you review the screenshots?

**Comment by gvwilson** [comment]
:+1: please merge

**Pull request merged**
